// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddUser(arg1, arg2) {
  return window['go']['main']['App']['AddUser'](arg1, arg2);
}

export function Initialize() {
  return window['go']['main']['App']['Initialize']();
}
