// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEntry() {
  return window['go']['main']['App']['CreateEntry']();
}

export function ImportVault() {
  return window['go']['main']['App']['ImportVault']();
}

export function InitialSetup() {
  return window['go']['main']['App']['InitialSetup']();
}
