// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateEntry():Promise<void>;

export function GetEntries():Promise<Array<main.Entry>>;

export function ImportVault():Promise<void>;

export function InitialSetup():Promise<void>;
