// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEntry(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateUser(arg1:string,arg2:string):Promise<void>;

export function GetRows(arg1:string):Promise<Array<Record<string, any>>>;

export function Initialize():Promise<void>;

export function RemoveRows(arg1:string,arg2:string,arg3:string):Promise<void>;
