// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEntry():Promise<void>;

export function ImportVault():Promise<void>;

export function InitialSetup():Promise<void>;
